# DAST scan using OWASP ZAP
name: DAST
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  pull-requests: write
  issues: write
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applications
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://demo.owasp-juice.shop'
          cmd_options: '-a -r report.html -w report.md -J report.json'
