name: DAST
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  pull-requests: write
  issues: write
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applications
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://demo.owasp-juice.shop'
          cmd_options: '-a'
          report_html: 'report.html'
          report_md: 'report.md'
          report_json: 'report.json'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-reports
          path: |
            report.html
            report.md
            report.json
